# Generated by Django 3.2.19 on 2023-06-15 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
